# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1365dc11533c6a3e1f8c4963c0aee3c1ec842027c8e8ec3c3a1a0b593f2cda4bce6fe78264b904db738c3eb7e001d348ff3e9002a8c0303902a98ab5bf9d47

test:
  secret_key_base: e5b07446b4139678b0f85568b7c223f44dc3412a7713d50166e334452bf2f929d9fc100126547a840db97487288c8a4a1c7fe4a2af202493665e89ca4bdce2f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
